# -*- coding: utf-8 -*-
"""GoogleDrive_Tutorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i41Whco5KIb7EuntKYwTVORAkAwCmlkF

# **Google Drive 檔案存取教學**

作者：黃健祐 Chien-Yu Huang

若有任何問題，歡迎來信至助教信箱 ntu-ml-2020spring-ta@googlegroups.com

Colab 可以透過兩種方式存取 Google Drive 的檔案：

**1. 透過檔案共用連結**

  一般來說，Google Drive 的檔案連結會是類似下面的結構：

  https://drive.google.com/open?id=1duQU7xqXRsOSPYeOR0zLiSA8g_LCFzoV
  
  其中 "open?id=" 後面的那一串亂碼稱為 **file_id**

  在 colab 中，我們可以直接用 **file_id** 下載檔案，優點是這個過程不需要再手動輸入任何訊息，但缺點是下載下來的檔案在程式執行完畢後就會消失，也就是每一次都必須重新下載，使得執行時間增加。
"""

# 下載 file_id 為 "1duQU7xqXRsOSPYeOR0zLiSA8g_LCFzoV" 的檔案，並將它命名為 Minori.jpg
!gdown --id '1duQU7xqXRsOSPYeOR0zLiSA8g_LCFzoV' --output Minori.jpg
# 列出目前目錄下所有的檔案
!ls

"""**2. 掛載自己的 Google Drive**

  透過 Google 提供的套件，我們可以讓 Colab 上的程式直接讀取自己的雲端硬碟。
  這個方法的好處是只要檔案存在於自己的雲端硬碟，就隨時都可以直接存取；相對地，缺點就是使用者得手動將檔案加入，並且在程式運行時要輸入連結 Google Drive 所需要的授權碼。
"""

# OpenCV 套件，和 Google Drive 無關
import cv2
# import Google Drive 套件
from google.colab import drive
# 將自己的雲端硬碟掛載上去
drive.mount('/content/gdrive')
# 透過 gdrive/My Drive/... 來存取檔案
img = cv2.imread('gdrive/My Drive/Minori.jpg')

"""助教們提供的 sample code 是使用第一種方式來取得檔案，如果同學在實作作業時有需要，可以自行將 code 換成第二種方式。"""